
title: Brora Rangers FC
email: digitalbrora@gmail.com
description: "Welcome to the Digital Dudgeon Park. All the news, views, reports and previews from Brora Rangers, Sutherland's Scottish Highland Football League Club"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

collections:
  fixtures:
    output: false
  clubs:
    output: true
  competitons:
    output: false
  people:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
