backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "build/images/uploads" # Media files will be stored here for processing prior to build
#public_folder: "/build/images/uploads" # Processed images are sent here

collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "News Articles" # Used in the UI
    folder: "_posts/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "news-article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "hidden", default: "news"}
      - {label: "Category", name: "news-category", widget: "select", options: ["Event News", "Squad News", "Match News", "Boardroom News", "Chairman's Chat"]}
      - {label: "Linked date", name: "linked-date", widget: "date", default: "", required: false}
      - {label: "People", name: 'tags', widget: "list", required: false}
      - {label: "Featured Image", name: "feature-image", widget: "image", required: false}
      - {label: "Short summary for Social Media", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "lotto" # Used in routes, e.g., /admin/collections/blog
    label: "Lotto Results" # Used in the UI
    folder: "_posts/lotto" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "lotto"}
      - {label: "Title", name: "title", widget: "string", default: "Cattachs Lotto"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draw Date", name: "draw-date", widget: "date"}
      - {label: "Category", name: "category", widget: "hidden", default: "lotto"}
      - {label: "Winning Numbers", name: "winning-numbers", widget: "list"}
      - {label: "Bonus Winners", name: "bonus-winners", widget: "list", required: false}
      - {label: "Jackpot Winners", name: "jackpot-winners", widget: "list", required: false}
      - {label: "Next Week's Bonus", name: "bonus", widget: "number", valueType: "int", default: 50 }
      - {label: "Next Week's Jackpot", name: "jackpot", widget: "number", valueType: "int", default: 1000 }
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Short summary for Social Media", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "previews" # Used in routes, e.g., /admin/collections/blog
    label: "Match Previews" # Used in the UI
    folder: "_posts/match-previews" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "match-preview"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Match Date", name: "match-date", widget: "date"}
      - {label: "Category", name: "category", widget: "hidden", default: "preview"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Short summary for Social Media", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "reports" # Used in routes, e.g., /admin/collections/blog
    label: "Match Reports" # Used in the UI
    folder: "_posts/match-reports" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "match-report"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Match Date", name: "match-date", widget: "date"}
      - {label: "Category", name: "category", widget: "hidden", default: "report"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Short summary for Social Media", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "fixtures" # Used in routes, e.g., /admin/collections/blog
    label: "Fixtures" # Used in the UI
    folder: "_fixtures" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{match-date}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", default: "Add a title in the format 'Buckie home' or 'Cove away' etc"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Season", name: "season", widget: "number", default: "2018"}
      - {label: "Competition", name: "competition", widget: "string"}
      - {label: "Match Date", name: "match-date", widget: "date"}
      - {label: "Kick Off", name: "kick-off", widget: "string", default: "15:00"}
      - {label: "Home Team", name: "home-team", widget: "relation", collection: "clubs", searchFields: ["title"], valueField: "title"}
      - {label: "Away Team", name: "away-team", widget: "relation", collection: "clubs", searchFields: ["title"], valueField: "title"}
      - {label: "Status", name: "status", widget: "select", options: ["outstanding", "postponed", "abandoned", "completed"], default: "outstanding"}
      - {label: "Home Team Score", name: "home-team-score", widget: "number", required: false}
      - {label: "Away Team Score", name: "away-team-score", widget: "number", required: false}
      - {label: "Home Team Score AET", name: "home-team-score-aet", widget: "number", required: false}
      - {label: "Away Team Score AET", name: "away-team-score-aet", widget: "number", required: false}
      - {label: "Home Team Score Pens", name: "home-team-score-pens", widget: "number", required: false}
      - {label: "Away Team Score Pens", name: "away-team-score-pens", widget: "number", required: false}

  - name: "clubs" # Used in routes, e.g., /admin/collections/blog
    label: "Clubs" # Used in the UI
    folder: "_clubs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Badge", name: "badge", widget: "image", required: false}
      - {label: "Ground", name: "ground", widget: "string"}

  - name: "competitons" # Used in routes, e.g., /admin/collections/blog
    label: "Competitions" # Used in the UI
    folder: "_competitions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Badge", name: "badge", widget: "image", required: false}
      - {label: "Sponsor", name: "sponsor", widget: "string"}

  - name: "people" # Used in routes, e.g., /admin/collections/blog
    label: "People" # Used in the UI
    folder: "_people" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Status", name: "status", widget: "select", options: ["current squad", "past squad", "management", "behind the scenes"]}
      - {label: "Sponsor", name: "sponsor", widget: "string"}
