backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "build/images/uploads" # Media files will be stored here for processing prior to build
#public_folder: "/build/images/uploads" # Processed images are sent here

collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "News Articles" # Used in the UI
    folder: "_posts/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "news-article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["boardroom", "chairmans-chat", "event", "match", "squad"]}
      - {label: "Featured Image", name: "feature-image", widget: "image", required: false}
      - {label: "Short summary for Social Media", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "reports" # Used in routes, e.g., /admin/collections/blog
    label: "Match Reports" # Used in the UI
    folder: "_posts/match-reports" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "match-report"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Match Date", name: "match-date", widget: "date"}
      - {label: "Category", name: "category", widget: "hidden", default: "report"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Short summary for Social Media", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "fixtures" # Used in routes, e.g., /admin/collections/blog
    label: "Fixtures" # Used in the UI
    folder: "_fixtures" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{competiton}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", default: "Add a title in the format 'Buckie home' or 'Cove away' etc"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Season", name: "season", widget: "number", default: "2018"}
      - {label: "Competition", name: "competiton", widget: "string"}
      - {label: "Match Date", name: "match-date", widget: "date"}
      - {label: "Home Team", name: "home-team", widget: "string"}
      - {label: "Away Team", name: "away-team", widget: "string"}
      - {label: "Home Team Score", name: "home-team-score", widget: "number", required: false}
      - {label: "Away Team Score", name: "away-team-score", widget: "number", required: false}
      - {label: "Home Team Score AET", name: "home-team-score-aet", widget: "number", required: false}
      - {label: "Away Team Score AET", name: "away-team-score-aet", widget: "number", required: false}
      - {label: "Home Team Score Pens", name: "home-team-score-pens", widget: "number", required: false}
      - {label: "Away Team Score Pens", name: "away-team-score-pens", widget: "number", required: false}

  - name: "lotto" # Used in routes, e.g., /admin/collections/blog
    label: "Lotto Results" # Used in the UI
    folder: "_posts/lotto" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "lotto"}
      - {label: "Title", name: "title", widget: "string", default: "Cattachs Lotto"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draw Date", name: "draw-date", widget: "date"}
      - {label: "Category", name: "category", widget: "hidden", default: "lotto"}
      - {label: "First Number", name: "first-lotto-number", widget: "number", valueType: "int", min: 1, max: 20 }
      - {label: "Second Number", name: "second-lotto-number", widget: "number", valueType: "int", min: 1, max: 20 }
      - {label: "Third Number", name: "third-lotto-number", widget: "number", valueType: "int", min: 1, max: 20 }
      - {label: "Fourth Number", name: "fourth-lotto-number", widget: "number", valueType: "int", min: 1, max: 20 }
      - {label: "Fifth Number", name: "fifth-lotto-number", widget: "number", valueType: "int", min: 1, max: 20 }
      - {label: "Next Week's Bonus", name: "bonus", widget: "number", valueType: "int", default: 50 }
      - {label: "Next Week's Jackpot", name: "jackpot", widget: "number", valueType: "int", default: 50 }
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Short summary for Social Media", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
